### ISSUE TITLE
vercelのURLがデプロイするたびに変わる

### ISSUE THREAD

**Issue by CobaltSato** [ytakahashi2020/airdrop_quest#20]
現在のurl
https://airdrop-quest-cufpamc13-qdrop-adventures.vercel.app

vercelのプランのupgradeなど、何かしらの運用上の考慮が必要です。

**Comment by mashharuki** [comment]
@CobaltSato このリポジトリの ownerである @ytakahashi2020 さんにデプロイしていただいた方が良いかもしれませんね・・。

vercelのURLは安定させたいですね・・。

**Comment by mashharuki** [comment]
vercelのupgradeプラン地味に高かった気がしてます！

**Comment by mashharuki** [comment]
yukiさんに修正きてもらったので解決ですね！

**Comment by mashharuki** [comment]
https://airdrop-quest-wine.vercel.app/game

**Comment by CobaltSato** [comment]
@mashharuki ありがとうございます！
